###############################################################################
# UFO Galaxy 64-Core MCP Matrix - Podman Compose Configuration
# Optimized for 24-Core MCP Service List
###############################################################################

version: "3.8"

networks:
  mcp-network:
    driver: bridge
  net_kernel:
    driver: bridge
  net_gateway:
    driver: bridge
  net_tools:
    driver: bridge
  net_phys:
    driver: bridge
    internal: true

volumes:
  oneapi_data:
  qdrant_data:
  redis_data:
  secrets_data:
  telemetry_data:
  logs_data:
  backup_data:
  sqlite_data:

services:
  # ========== 架构核心 (3000+) ==========
  
  # 1. OneAPI 网关 (Node 01)
  mcp-oneapi:
    image: ghcr.io/songquanpeng/one-api:latest
    container_name: mcp-oneapi
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - oneapi_data:/data
    networks:
      - mcp-network
      - net_kernel

  # 2. 任务调度器 (Node 02)
  mcp-tasker:
    build: ./nodes/Node_02_Tasker
    container_name: mcp-tasker
    ports:
      - "3002:3002"
    networks:
      - mcp-network
      - net_kernel

  # 3. 搜索服务 (Node 09)
  mcp-search:
    build: ./nodes/Node_09_Search
    container_name: mcp-search
    ports:
      - "3003:3003"
    networks:
      - mcp-network
      - net_tools

  # 4. YouTube 工具 (Node 14)
  mcp-youtube:
    build: ./nodes/Node_14_FFmpeg
    container_name: mcp-youtube
    ports:
      - "3004:3004"
    networks:
      - mcp-network
      - net_tools

  # 5. 分类器 (Node 58)
  mcp-classifier:
    build: ./nodes/Node_58_ModelRouter
    container_name: mcp-classifier
    ports:
      - "3005:3005"
    networks:
      - mcp-network
      - net_gateway

  # 6. 系统监控 (Node 64)
  mcp-monitoring:
    build: ./nodes/Node_64_Telemetry
    container_name: mcp-monitoring
    ports:
      - "19999:19999"
    networks:
      - mcp-network
      - net_kernel

  # 7. Qdrant 向量数据库 (Node 20)
  mcp-qdrant:
    image: qdrant/qdrant:latest
    container_name: mcp-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - mcp-network
      - net_tools

  # 8. OCR 服务 (Node 15)
  mcp-ocr:
    build: ./nodes/Node_15_OCR
    container_name: mcp-ocr
    ports:
      - "5001:5001"
    networks:
      - mcp-network
      - net_tools

  # 9. UI 分析器 (Node 45)
  mcp-ui-analyzer:
    build: ./nodes/Node_45_DesktopAutomation
    container_name: mcp-ui-analyzer
    ports:
      - "4723:4723"
    networks:
      - mcp-network
      - net_phys

  # ========== 功能工具箱 (8001-8015) ==========

  # 1. Filesystem 工具 (Node 06)
  mcp-filesystem:
    build: ./nodes/Node_06_Filesystem
    container_name: mcp-filesystem
    ports:
      - "8001:8001"
    networks:
      - mcp-network
      - net_tools

  # 2. GitHub Tools (Node 11)
  mcp-github-tools:
    build: ./nodes/Node_11_GitHub
    container_name: mcp-github-tools
    ports:
      - "8002:8002"
    networks:
      - mcp-network
      - net_tools

  # 3. Memory 服务 (Node 00)
  mcp-memory:
    build: ./nodes/Node_00_StateMachine
    container_name: mcp-memory
    ports:
      - "8003:8003"
    networks:
      - mcp-network
      - net_kernel

  # 4. Notion 集成 (Node 21)
  mcp-notion:
    build: ./nodes/Node_21_Notion
    container_name: mcp-notion
    ports:
      - "8004:8004"
    networks:
      - mcp-network
      - net_tools

  # 5. Playwright 工具 (Node 45)
  mcp-playwright:
    image: mcr.microsoft.com/playwright:v1.40.0-jammy
    container_name: mcp-playwright
    ports:
      - "8005:8005"
    networks:
      - mcp-network
      - net_phys

  # 6. Slack 集成 (Node 10)
  mcp-slack:
    build: ./nodes/Node_10_Slack
    container_name: mcp-slack
    ports:
      - "8006:8006"
    networks:
      - mcp-network
      - net_tools

  # 7. SQLite DB (Node 13)
  mcp-sqlite:
    build: ./nodes/Node_13_SQLite
    container_name: mcp-sqlite
    ports:
      - "8007:8007"
    volumes:
      - sqlite_data:/app/data
    networks:
      - mcp-network
      - net_tools

  # 8. Brave Search (Node 22)
  mcp-brave:
    build: ./nodes/Node_22_BraveSearch
    container_name: mcp-brave
    ports:
      - "8008:8008"
    networks:
      - mcp-network
      - net_tools

  # 9. Docker Manager (Node 66)
  mcp-docker:
    build: ./nodes/Node_66_ConfigManager
    container_name: mcp-docker
    ports:
      - "8009:8009"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mcp-network
      - net_kernel

  # 10. GitHub Official (Node 11)
  mcp-github-official:
    build: ./nodes/Node_11_GitHub
    container_name: mcp-github-official
    ports:
      - "8010:8010"
    networks:
      - mcp-network
      - net_tools

  # 11. Sequential Thinking (Node 56)
  mcp-thinking:
    build: ./nodes/Node_56_AgentSwarm
    container_name: mcp-thinking
    ports:
      - "8011:8011"
    networks:
      - mcp-network
      - net_gateway

  # 12. FFmpeg Tools (Node 14)
  mcp-ffmpeg:
    image: jrottenberg/ffmpeg:latest
    container_name: mcp-ffmpeg
    ports:
      - "8012:8012"
    networks:
      - mcp-network
      - net_tools

  # 13. Arxiv Research (Node 13)
  mcp-arxiv:
    build: ./nodes/Node_13_SQLite
    container_name: mcp-arxiv
    ports:
      - "8013:8013"
    networks:
      - mcp-network
      - net_tools

  # 14. Terminal 服务 (Node 48)
  mcp-terminal:
    build: ./nodes/Node_48_Serial
    container_name: mcp-terminal
    ports:
      - "8014:8014"
    networks:
      - mcp-network
      - net_phys

  # 15. Weather Service (Node 24)
  mcp-weather:
    build: ./nodes/Node_24_Weather
    container_name: mcp-weather
    ports:
      - "8015:8015"
    networks:
      - mcp-network
      - net_tools

  # ========== 基础服务 ==========
  redis:
    image: docker.io/redis:7-alpine
    container_name: ufo_redis
    volumes:
      - redis_data:/data
    networks:
      - net_kernel
    restart: unless-stopped
